
export const sendTelegramMessage = async (botToken, chatId, message) => {
    if (!botToken || !chatId) return;

    const url = `https://api.telegram.org/bot${botToken}/sendMessage`;
    const payload = {
        chat_id: chatId,
        text: message,
        parse_mode: 'Markdown'
    };

    try {
        const response = await fetch(url, {
            method: 'POST',
            headers: {
                'Content-Type': 'application/json'
            },
            body: JSON.stringify(payload)
        });

        if (!response.ok) {
            console.error('Telegram API Error:', await response.text());
            return false;
        }
        return true;
    } catch (error) {
        console.error('Failed to send Telegram message:', error);
        return false;
    }
};

export const formatSignalMessage = (signal, symbol, timeframe) => {
    const emoji = signal.type === 'LONG' ? '🟢' : '🔴';

    let tpSection = `*TP:* $${signal.tp.toLocaleString()}`;
    if (signal.tp1 && signal.tp2) {
        tpSection = `*TP1:* $${signal.tp1.toLocaleString()}
*TP2:* $${signal.tp2.toLocaleString()}
*TP3:* $${signal.tp3.toLocaleString()}`;
    }

    return `
${emoji} *NEW SIGNAL: ${symbol}* ${emoji}

*Type:* ${signal.type}
*Timeframe:* ${timeframe}
*Entry:* $${signal.entry.toLocaleString()}
${tpSection}
*SL:* $${signal.sl.toLocaleString()}
*Leverage:* ${signal.leverage}x

*Reason:* ${signal.reason}

*AI Sentiment:* ${signal.indicators?.sentiment > 0 ? 'Positive' : signal.indicators?.sentiment < 0 ? 'Negative' : 'Neutral'} (${(signal.indicators?.sentiment || 0).toFixed(1)})
*Trend Strength (ADX):* ${(signal.indicators?.adx || 0).toFixed(1)}

_Generated by ABC Terminal_
    `.trim();
};
